# Generated by Django 4.0.5 on 2022-06-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=250, unique=True)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outro', 'Outro')], max_length=250)),
                ('idade', models.PositiveIntegerField(default=16)),
                ('presidente', models.CharField(choices=[('Jair Bolsonaro', 'Jair Bolsonaro'), ('Luiz Inacio Lula da Silva', 'Luiz Inacio Lula Da Silva'), ('Marina Silva', 'Marina Silva'), ('Ciro Gomes', 'Ciro Gomes'), ('nulo', 'Nulo'), ('branco', 'Branco')], max_length=250)),
                ('audio', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
